### ISSUE TITLE
Provide a complete environment to simplify development

### ISSUE THREAD

**Issue by MaXal** [karashevich/GuiScriptRecorder#4]
At the moment it's not possible to checkout a project and to start plugin development since all configuration is missing.
It's very hard to guess what files/libraries should be used, where they should be located and which name they should have. For example, `kotlin-compiler.jar` should be located inside resources folders since inclusion in classpath will lead to `MethodNotFoundException` due to a missing method in JBUI class. Also, the file should be named precisely `kotlin-compiler.jar` otherwise compilation will fail.

Probably it may be useful to write gradle script that will manage all dependencies and pack the plugin into zip for distribution.

**Comment by karashevich** [comment]
Yeah, I agree with you. I've moved GuiScriptRecorder plugin to Gradle and switched all dependencies to maven. So, since version 0.5.15 no need to download additional jars and libraries to start using the plugin.
